### PR TITLE
MGDAPI-5458 - refactor: remove blocking gcp calls

### PR DESCRIPTION
**Pull request by KevFan**
## Overview

Jira: issues.redhat.com/browse/MGDAPI-5458

## Verification

- Clone this branch
- Run `make cluster/prepare`
- Run `make run` against a GCP cluster
- Seed Postgres
```
PROVIDER=gcp make cluster/seed/postgres
```
* Verify phase is in progress during ip address range or connection service creation
```
oc get postgres example-postgres -n cloud-resource-operator -o json | jq '.status'
```
image
* Delete postgres
- Seed Redis
```
PROVIDER=gcp make cluster/seed/redis
```
- Verify phase is in progress during ip address range or connection service creation
```
oc get redis example-redis -n cloud-resource-operator -o json | jq '.status'
```

image
* Delete redis
## Checklist
- [ ] This PR includes a change to an instance type, I have used script `hack/<provider>/supported_types.sh` and attached the result below

### CODE REVIEW

**Comment by KevFan** [comment]
@adam-cattermole if you can have a quick look to make sure this is the right direction

**Comment by adam-cattermole** [comment]
@KevFan Yep this looks like the right direction, couple changes required still:

* Address might be nil in this log https://github.com/integr8ly/cloud-resource-operator/pull/678/files#diff-aa1db70483adcd55500859d5b2a1f4ce5fc735fe75a0f9a0fff1f8276fe830b4R130
* Now that we do not wait for the resources to be created we need to make sure the reconcilers return `in progress` if the service connection is not ready / has not been created yet - see here in the postgres reconciler https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/gcp/provider_postgres.go#L130-L139

**Comment by carlkyrillos** [comment]
Reviewed changed files and verified that the Postgres|Redis phase is set to `in progress` during IP address range or connection service creation

postgres-phase-verification
redis-phase-verification

/lgtm

**Pull request merged**
