### PR TITLE
MGDAPI-6233 - Review CRO dependabot PRs

### PR DESCRIPTION
**Pull request by valerymo**
Jira: https://issues.redhat.com/browse/MGDAPI-6233

Address dependabot PRs: 
- https://github.com/integr8ly/cloud-resource-operator/pull/661
- https://github.com/integr8ly/cloud-resource-operator/pull/699

## Overview

Jira: <jira-id>

## Verification

- Clone this branch
- Run `make cluster/prepare`
- Run `make run`
- Ensure...

## Checklist
- [ ] This PR includes a change to an instance type, I have used script `hack/<provider>/supported_types.sh` and attached the result below

### CODE REVIEW

**Comment by valerymo** [comment]
Local checking of `gosec` is passing ok
[vmogilev@vmogilev cloud-resource-operator] (MGDAPI-6233)$ make gosec
....
Results:
Summary:
  Gosec  : 2.18.2
  Files  : 101
  Lines  : 20942
  Nosec  : 9
  Issues : 0

**Comment by valerymo** [comment]
recheck gosec locally:

Results:
Summary:
  Gosec  : 2.18.2
  Files  : 101
  Lines  : 20942
  Nosec  : 9
  Issues : 0

[vmogilev@vmogilev cloud-resource-operator] (MGDAPI-6233)$ date
Wed Jan 31 13:50:17 IST 2024

**Comment by valerymo** [comment]
[gosec] 2024/02/06 15:53:42 Checking file: /home/vmogilev/go/cloud-resource-operator/pkg/providers/config_moq.go
[gosec] 2024/02/06 15:53:42 Checking file: /home/vmogilev/go/cloud-resource-operator/pkg/providers/types.go
[gosec] 2024/02/06 15:53:42 Checking file: /home/vmogilev/go/cloud-resource-operator/pkg/providers/types_moq.go
Results:


Summary:
  Gosec  : 2.18.2
  Files  : 101
  Lines  : 20836
  Nosec  : 9
  Issues : 0

[vmogilev@vmogilev cloud-resource-operator] (MGDAPI-5690)$ date
Tue Feb  6 15:53:46 IST 2024
[vmogilev@vmogilev cloud-resource-operator] (MGDAPI-5690)$

**Comment by MStokluska** [comment]
/close
done as part of https://github.com/integr8ly/cloud-resource-operator/pull/798/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Pull request closed without merging**
