### PR TITLE
MGDAPI-5074 - replace config type with openshift API

### PR DESCRIPTION
**Pull request by adam-cattermole**
## Overview

[MGDAPI-5074](https://issues.redhat.com/browse/MGDAPI-5074)

## Changes

- Removed config folder in favour of github.com/openshift/api@release-4.11
- Also fixed many lint issues (mostly involving tests):
	- Updated all uses of deprecated test function `fake.NewFakeClientWithScheme` in favour of our `moqClient.NewSigsClientMoqWithScheme` version, and updated the moqClient to use `fake.NewClientBuilder()`
	- Removed all duplicate type definitions - these were present across many files
	- Replaced `errors.New(fmt.Sprintf(..))` occurrences with `fmt.Errorf(..)`
	- Reduced lint issues from 313 -> 32

## Verification

I have tested that this is functional on a GCP cluster, but it would be worth the reviewer testing on an AWS CCS cluster.

- Provision an AWS CCS cluster
- Deploy CRO from this branch
```
make cluster/prepare
make run
```
- Create postgres/redis/blobstorage CR's
```
PROVIDER=aws make cluster/seed/postgres
PROVIDER=aws make cluster/seed/redis
PROVIDER=aws make cluster/seed/blobstorage
```
- Delete resources
```
oc delete postgres example-postgres
oc delete redis example-redis
oc delete blobstorage example-blobstorage
```

### CODE REVIEW

**Review by cecobask — APPROVED** [review]
After following the verification steps, I can confirm that all the resources were provisioned and cleaned up successfully on an AWS CCS cluster.
The changes look good to me, thanks for doing the linting! There seems to have been quite a lot of imports with different names out there 😄 How did you discover these linting issues? 

/lgtm

**Comment by adam-cattermole** [comment]
Awesome, thanks for the review! In VS Code the Go extension can be configured to lint the package/workspace and I have mine set to lint on save so I've seen them for a while and finally got round to fixing them

**Pull request merged**
