### PR TITLE
MGDAPI-5081 - Updates to CRO GCP for RHOAM

### PR DESCRIPTION
**Pull request by adam-cattermole**
## Overview

[MGDAPI-5081](https://issues.redhat.com/browse/MGDAPI-5081)

## Changes

- Modified the strategy client code for use with both AWS and GCP cloud providers
- Made some modifications to the postgres configuration to avoid a nil pointer and to set up the network configuration to use private network

## Verification

Verify alongside related RHOAM PR integr8ly/integreatly-operator#3100 - this CRO PR should be merged first!

### CODE REVIEW

**Review by cecobask — APPROVED** [review]
The code changes look good to me. I won't perform any verification steps here, but I will verify it together with https://github.com/integr8ly/integreatly-operator/pull/3100.

/lgtm

**Comment by austincunningham** [comment]
https://github.com/integr8ly/integreatly-operator/pull/3100 is failing e2e but looks like it was verified ?

**Comment by adam-cattermole** [comment]
@austincunningham e2e was passing, but it reran after minor commit from review and hit the failed to provision clusters flake.. will rerun

**Comment by adam-cattermole** [comment]
@austincunningham Looks like they're passing now

**Pull request merged**
