### PR TITLE
set AutoMinorVersionUpgrade to false by default

### PR DESCRIPTION
**Pull request by briangallagher**
## Overview

Jira: https://issues.redhat.com/browse/INTLY-10247

## Verification

- Clone this branch
- Run `make cluster/prepare`
- Run `make run`
- Create a Postgres CR and ensure AutoMinorVersionUpgrade is set to false by default

`aws rds describe-db-instances | grep AutoMinorVersionUpgrade`

### CODE REVIEW

**Comment by briangallagher** [comment]
@ciaranRoche @aidenkeating Could you review?

**Comment by briangallagher** [comment]
@dimitraz Can you review?

**Comment by austincunningham** [comment]
Verified works as expected 
/lgtm
/approved

**Pull request merged**
