### PR TITLE
Added health check for CRO manager setup

### PR DESCRIPTION
**Pull request by Ankit152**
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>

## Overview

Adds health and ready checks for the CRO `manager`.
Jira: [MGDAPI-3288](https://issues.redhat.com/browse/MGDAPI-3288)

### CODE REVIEW

**Comment by austincunningham** [comment]
@Ankit152 after a quick review I think you are missing some elements see how it was done in integreatly-operator https://github.com/integr8ly/integreatly-operator/pull/2879

**Comment by austincunningham** [comment]
> @Ankit152 after a quick review I think you are missing some elements see how it was done in integreatly-operator [integr8ly/integreatly-operator#2879](https://github.com/integr8ly/integreatly-operator/pull/2879)

particularly the health port https://github.com/integr8ly/integreatly-operator/pull/2879/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R95 and adding it to the manager https://github.com/integr8ly/integreatly-operator/pull/2879/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R120

**Comment by Ankit152** [comment]
Yeah. I missed that. Adding the health port to the manager. 🙂

**Comment by austincunningham** [comment]
looking at the e2e failure `create redis test failure: could not create example redis: redis.integreatly.org "example-redis" already exists` reason is not related to this PR

**Comment by austincunningham** [comment]
## Verification
ran the operator locally 
```bash
make cluster/prepare
make run
```
can see the healthz endpoint is returning and ok 
```bash
curl localhost:8081/health 
404 page not found
➜  cloud-resource-operator git:(health-check) curl localhost:8081/healthz
ok%           
```          
Think I will need to build a dev image to finish the verification

**Comment by austincunningham** [comment]
> looking at the e2e failure `create redis test failure: could not create example redis: redis.integreatly.org "example-redis" already exists` reason is not related to this PR

@adam-cattermole  spotted this in the e2e logs
```bash
The Deployment "cloud-resource-operator" is invalid: 
push_pin
* spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
* spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
make: [cluster/deploy] Error 1 (ignored)
```
I am thinking that you have a yaml spacing/formating issue in the manager.yaml https://github.com/integr8ly/cloud-resource-operator/pull/601/files#diff-ce0d597a9e5f20a8fe61c3ba5e6185a6b90cfef2c00bb5b5ef3e97b15b79f480R25-R42

**Comment by austincunningham** [comment]
> > looking at the e2e failure `create redis test failure: could not create example redis: redis.integreatly.org "example-redis" already exists` reason is not related to this PR
> 
> @adam-cattermole spotted this in the e2e logs
> 
> ```shell
> The Deployment "cloud-resource-operator" is invalid: 
> push_pin
> * spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
> * spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
> make: [cluster/deploy] Error 1 (ignored)
> ```
> 
> I am thinking that you have a yaml spacing/formating issue in the manager.yaml https://github.com/integr8ly/cloud-resource-operator/pull/601/files#diff-ce0d597a9e5f20a8fe61c3ba5e6185a6b90cfef2c00bb5b5ef3e97b15b79f480R25-R42

Kudos @adam-cattermole again
https://github.com/kubernetes/kubernetes/issues/37218#issuecomment-372887460 looks like you can't have a exec and a httpGet together , think an ls should be enough https://github.com/integr8ly/integreatly-operator/pull/2879/files#diff-ce0d597a9e5f20a8fe61c3ba5e6185a6b90cfef2c00bb5b5ef3e97b15b79f480R67-R69

**Pull request merged**
