### PR TITLE
Create version 0.22.2

### PR DESCRIPTION
**Pull request by briangallagher**
## Overview

Bump CRO version to v0.22.2
https://issues.redhat.com/browse/INTLY-10249

## Verification
- Run end to end tests
- Install operator and confirm version 0.22.2

### CODE REVIEW

**Comment by briangallagher** [comment]
@aidenkeating @ciaranRoche @austincunningham @dimitraz Anyone time to review?

**Comment by austincunningham** [comment]
need to bump the versions here https://github.com/integr8ly/cloud-resource-operator/pull/191/files#diff-f6bf0ae0d21c9408c6624174da11dafb369ce306f2cdcea704285d8acc87e19eR4

**Comment by briangallagher** [comment]
> need to bump the versions here https://github.com/integr8ly/cloud-resource-operator/pull/191/files#diff-f6bf0ae0d21c9408c6624174da11dafb369ce306f2cdcea704285d8acc87e19eR4

@austincunningham done

**Review by austincunningham — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
