### PR TITLE
intly-7899 fix failing availability metric

### PR DESCRIPTION
**Pull request by aidenkeating**
jira: https://issues.redhat.com/browse/INTLY-7899

verification:
- 1499266 for postgres
- e8df075 for redis

### CODE REVIEW

**Comment by aidenkeating** [comment]
@dimitraz Mind taking a look, provisioned in the `intly-7899` namespace in the `monitoring-byoc` cluster. Basically:

- Force a backup on RDS
- Run `curl localhost:8383/metrics 2>&1 | grep cro_postgres_available` and ensure the value is always `1`

- Force a snapshot on RDS
- Run `curl localhost:8383/metrics 2>&1 | grep cro_redis_available` and ensure the value is always `1`. This would happen anyway because we have two clusters in the replication group, but it hardens the Elasticache logic

**Comment by dimitraz** [comment]
@aidenkeating sure, looking now :eyes:

**Comment by aidenkeating** [comment]
26246204d675085d5a524c506047989109b7dad9 - ksm style status metric

@dimitraz 

verification:

- create a redis, postgres, blobstorage, redissnapshot and postgresnapshot custom resource
- wait for the operator to reconcile on them
- run `curl localhost:8383/metrics 2>&1 | grep _status_phase` and ensure 5 metrics are exposed for each resource type, with the `status` label as each different phase
- ensure the value is `1` for only one status, and that it's the correct status (matches the cr)
- force a failure state on a custom resource, ensure it changes state (postgres and redis)

**Comment by dimitraz** [comment]
## Redis
CR: 
```yaml
status:
  message: 'successfully created and tagged, aws elasticache status is available'
  phase: complete
```
Metrics: 
```
cro_redis_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-u7f3",namespace="intly-7899",productName="productName",resourceID="example-redis",statusPhase="complete",strategy="aws-elasticache"} 1
cro_redis_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-u7f3",namespace="intly-7899",productName="productName",resourceID="example-redis",statusPhase="deletion in progress",strategy="aws-elasticache"} 0
cro_redis_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-u7f3",namespace="intly-7899",productName="productName",resourceID="example-redis",statusPhase="failed",strategy="aws-elasticache"} 0
cro_redis_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-u7f3",namespace="intly-7899",productName="productName",resourceID="example-redis",statusPhase="in progress",strategy="aws-elasticache"} 0
cro_redis_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-u7f3",namespace="intly-7899",productName="productName",resourceID="example-redis",statusPhase="paused",strategy="aws-elasticache"} 0
```

## Redis Snapshot
### Failed

CR: 
```yml
status:
  message: 'failed to get redis cr : Redis.integreatly.org "not-exists" not found'
  phase: failed
```

Metrics:
```
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="",namespace="intly-7899",productName="",resourceID="this-will-fail",statusPhase="complete",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="",namespace="intly-7899",productName="",resourceID="this-will-fail",statusPhase="deletion in progress",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="",namespace="intly-7899",productName="",resourceID="this-will-fail",statusPhase="failed",strategy="aws-elasticache"} 1
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="",namespace="intly-7899",productName="",resourceID="this-will-fail",statusPhase="in progress",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="",namespace="intly-7899",productName="",resourceID="this-will-fail",statusPhase="paused",strategy="aws-elasticache"} 0
```

### Complete
CR: 
```yml
status:
  message: snapshot created
  phase: complete
```
Metrics:
```
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-z72g",namespace="intly-7899",productName="",resourceID="example-redissnapshot",statusPhase="complete",strategy="aws-elasticache"} 1
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-z72g",namespace="intly-7899",productName="",resourceID="example-redissnapshot",statusPhase="deletion in progress",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-z72g",namespace="intly-7899",productName="",resourceID="example-redissnapshot",statusPhase="failed",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-z72g",namespace="intly-7899",productName="",resourceID="example-redissnapshot",statusPhase="in progress",strategy="aws-elasticache"} 0
cro_redis_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-z72g",namespace="intly-7899",productName="",resourceID="example-redissnapshot",statusPhase="paused",strategy="aws-elasticache"} 0
```

**Comment by dimitraz** [comment]
## Postgres
### In progress
CR: 
```yml
status:
  message: 'createRDSInstance() in progress, current aws rds resource status is creating'
  phase: in progress
```
Metrics:
```
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-ugzg",namespace="intly-7899",productName="productName",resourceID="example-postgres2",statusPhase="complete",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-ugzg",namespace="intly-7899",productName="productName",resourceID="example-postgres2",statusPhase="deletion in progress",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-ugzg",namespace="intly-7899",productName="productName",resourceID="example-postgres2",statusPhase="failed",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-ugzg",namespace="intly-7899",productName="productName",resourceID="example-postgres2",statusPhase="in progress",strategy="aws-rds"} 1
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-ugzg",namespace="intly-7899",productName="productName",resourceID="example-postgres2",statusPhase="paused",strategy="aws-rds"} 0
```
### Failed
CR:
```yml
status:
  message: >-
    Postgres CR example-postgres in intly-7899 namespace has resourceIdentifier
    annotation with value monitoringbyocszfbbintly7899example-k523, but no
    corresponding RDS instance was found: Postgres CR example-postgres in
    intly-7899 namespace has resourceIdentifier annotation with value
    monitoringbyocszfbbintly7899example-k523, but no corresponding RDS instance
    was found
  phase: failed
```

Metrics:
```
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-k523",namespace="intly-7899",productName="productName",resourceID="example-postgres",statusPhase="complete",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-k523",namespace="intly-7899",productName="productName",resourceID="example-postgres",statusPhase="deletion in progress",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-k523",namespace="intly-7899",productName="productName",resourceID="example-postgres",statusPhase="failed",strategy="aws-rds"} 1
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-k523",namespace="intly-7899",productName="productName",resourceID="example-postgres",statusPhase="in progress",strategy="aws-rds"} 0
cro_postgres_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-k523",namespace="intly-7899",productName="productName",resourceID="example-postgres",statusPhase="paused",strategy="aws-rds"} 0
```

## Postgres snapshot
CR:
```yml
status:
  message: error creating rds snapshot error creating rds snapshot
  phase: failed
```

Metrics:
```
cro_postgres_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-gwzo",namespace="intly-7899",productName="",resourceID="example-postgressnapshot",statusPhase="complete",strategy="aws-rds"} 0
cro_postgres_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-gwzo",namespace="intly-7899",productName="",resourceID="example-postgressnapshot",statusPhase="deletion in progress",strategy="aws-rds"} 0
cro_postgres_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-gwzo",namespace="intly-7899",productName="",resourceID="example-postgressnapshot",statusPhase="failed",strategy="aws-rds"} 1
cro_postgres_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-gwzo",namespace="intly-7899",productName="",resourceID="example-postgressnapshot",statusPhase="in progress",strategy="aws-rds"} 0
cro_postgres_snapshot_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-gwzo",namespace="intly-7899",productName="",resourceID="example-postgressnapshot",statusPhase="paused",strategy="aws-rds"} 0
```

**Comment by dimitraz** [comment]
## Blobstorage
### Complete
CR:
```yml
status:
  message: successfully created and tagged
  phase: complete
```

Metrics:
```
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-oyio",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage",statusPhase="complete",strategy="aws-s3"} 1
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-oyio",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage",statusPhase="deletion in progress",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-oyio",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage",statusPhase="failed",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-oyio",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage",statusPhase="in progress",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-oyio",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage",statusPhase="paused",strategy="aws-s3"} 0
```

### Failed
CR: 
```yml
status:
  message: failed to reconcile instance secret
  phase: failed
```

Metrics
```
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-cvgv",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage2",statusPhase="complete",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-cvgv",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage2",statusPhase="deletion in progress",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-cvgv",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage2",statusPhase="failed",strategy="aws-s3"} 1
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-cvgv",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage2",statusPhase="in progress",strategy="aws-s3"} 0
cro_blobstorage_status_phase{clusterID="monitoring-byoc-szfbb",instanceID="monitoringbyocszfbbintly7899example-cvgv",namespace="intly-7899",productName="ProductName",resourceID="example-blobstorage2",statusPhase="paused",strategy="aws-s3"} 0
```

**Pull request merged**
