### PR TITLE
MGDAPI-3258 - Update Go dependency to 1.17

### PR DESCRIPTION
**Pull request by adam-cattermole**
## Overview

Jira: [MGDAPI-3258](https://issues.redhat.com/browse/MGDAPI-3258)

## Changes
* Updated Go version for CRO to 1.17
* Updated `controller-gen` from `v0.3.0` to `v0.8.0` (Go  version 1.13 -> 1.17)
* Updated `kustomize` from `v3@3.5.4` to `v4@v4.4.1` (Go version 1.13 -> 1.16)

## Verification
* Check `make code/gen` works as expected with new controller-gen version

Ensure main functions of CRO are unaffected, on CCS cluster:
* `make cluster/prepare`
* `make run`
* Deploy `Postgres`, `BlobStorage`, `Redis` CRs
* Delete `Postgres`, `BlobStorage`, `Redis` CRs
(Check AWS resources to ensure this completes as expected)

## Checklist
- [ ] This PR includes a change to an instance type, I have used script `hack/<provider>/supported_types.sh` and attached the result below

### CODE REVIEW

**Comment by adam-cattermole** [comment]
Put in a PR to update go version prow uses: openshift/release#25726.

Steps to take:
* Test the prow PR
* Verify this change
* Merge prow update
* Run tests here
* Merge assuming all is well

**Comment by adam-cattermole** [comment]
Prow PR merged.
/retest

**Comment by austincunningham** [comment]
@adam-cattermole readme is still pointing at 1.13
https://github.com/integr8ly/cloud-resource-operator/blame/master/README.md#L39-L42

**Comment by adam-cattermole** [comment]
Good spot, updated.

**Comment by austincunningham** [comment]
# Verified
- [x] make code/gen
```bash
make code/gen
go get github.com/matryer/moq
go get: added github.com/matryer/moq v0.2.5
go mod vendor
/home/austincunningham/go/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/austincunningham/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/home/austincunningham/go/bin/controller-gen rbac:roleName=manager-role webhook paths="./..."
```
- [x] make cluster/prepare
- [x] make run
- [x] make cluster/seed/managed/blobstorage
```bash
oc get blobstorages.integreatly.org example-blobstorage -ojson | jq '.status'
{
  "message": "successfully created and tagged",
  "phase": "complete",
  "provider": "aws-s3",
  "secretRef": {
    "name": "example-blobstorage-sec"
  },
  "strategy": "aws"
}
```
- [x] make cluster/seed/managed/postgres
```bash
oc get postgres example-postgres -ojson | jq .'status' 
{
  "message": "rds instance rhmicloudsccsrzqmfcloudresourceoper-6b33 is as expected, aws rds status is available",
  "phase": "complete",
  "provider": "aws-rds",
  "secretRef": {
    "name": "example-postgres-sec"
  },
  "strategy": "aws",
  "version": "10.16"
}
```
- [x] make cluster/seed/managed/redis
```bash
oc get redis example-redis -ojson | jq '.status'
{
  "message": "successfully created and tagged, aws elasticache status is available",
  "phase": "complete",
  "provider": "aws-elasticache",
  "secretRef": {
    "name": "example-redis-sec"
  },
  "strategy": "aws",
  "version": "5.0.6"
}
```

/lgtm
/approve

**Pull request merged**
