### PR TITLE
bump version to 0.4.0

### PR DESCRIPTION
**Pull request by dimitraz**
## Overview

Jira: <jira-id>

## Verification

- Clone this branch
- Run `make cluster/prepare`
- Run `make run`
- Ensure...

### CODE REVIEW

**Comment by austincunningham** [comment]
/lgtm
Verifying

**Comment by ciaranRoche** [comment]
/hold

Just putting a hold on this, till we get all other PR's merged, then we can bump version :)

**Comment by austincunningham** [comment]
Good call, its verified anyway. can stick approved on it at any time.

**Pull request merged**
