### PR TITLE
grant unlimited power

### PR DESCRIPTION
**Pull request by aidenkeating**
they have taken the oath.

in brightest day, in blackest night,
no evil shall escape my sight.
let those who worship evil's might,
beware my power - cloud resource operator's light!

we must grant them the power.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
And in time I hope to make cloud resource operator's a name to be feared by evil doers everywhere.

**Comment by aidenkeating** [comment]
/lgtm
/approve

I think this is all that's required

**Comment by darahayes** [comment]
Oh hey guys, can I get added as a reviewer also? 😄

**Comment by aidenkeating** [comment]
@darahayes Of course, one moment, luckily Prow is too good to let me LGTM my own PR

**Pull request merged**
