### PR TITLE
MGDAPI-3228 - update CRO readme

### PR DESCRIPTION
**Pull request by adam-cattermole**
## Overview

Jira: [MGDAPI-3228](https://issues.redhat.com/browse/MGDAPI-3228)

## Changes

Added instructions for deploy and upgrade scenarios for CRO through OLM.

## Checklist
- [ ] This PR includes a change to an instance type, I have used script `hack/<provider>/supported_types.sh` and attached the result below

### CODE REVIEW

**Review by austincunningham — COMMENTED** [review]
Changes look good , can you update https://github.com/integr8ly/cloud-resource-operator/blame/master/README.md#L34 the yq version also can you add the operator-sdk version to the Prerequisites

**Comment by adam-cattermole** [comment]
> Changes look good , can you update https://github.com/integr8ly/cloud-resource-operator/blame/master/README.md#L34 the yq version also can you add the operator-sdk version to the Prerequisites

Thanks - updated these versions

**Pull request merged**
