### PR TITLE
MDGAPI-1857: version bump v0.26.0

### PR DESCRIPTION
**Pull request by austincunningham**
## Overview

Jira: <jira-id>MDGAPI-1857

## Verification

- version bump

### CODE REVIEW

**Comment by austincunningham** [comment]
running 
```bash
make vendor/fix 
go mod tidy
go: finding module for package github.com/elazarl/goproxy/ext/image
go: found github.com/elazarl/goproxy/ext/image in github.com/elazarl/goproxy/ext v0.0.0-20210110162100-a92cc753f88e
go mod vendor
```
fixed this locally
```bash
make vendor/check
go mod tidy
go mod vendor
git diff --exit-code vendor/
# git is clean
git status
On branch MGDAPI-1857-version-bump
nothing to commit, working tree clean
```
prow is being flaky and falling vendor check for some other reason
/test vendor

**Comment by MStokluska** [comment]
@austincunningham I was able to update the vendor folder locally and it seems that committing it was not an issue too, can we try updating the vendor folder? I don't think it's flaky but just missing the dependencies.

**Comment by MStokluska** [comment]
Verified it with RHOAM master > 0.26.0 skipping 0.25.0 of CRO. All works as expected. Upgrade and uninstallation works. 
Good job
/lgtm

**Pull request merged**
